tasks:
    command-0:
        command: yarn start
        dependsOn:
            - init-000
        description: init task migrated from .gitpod.yml
        name: 'Task 0: command'
        triggeredBy:
            - postDevcontainerStart
    init-000:
        command: yarn
        description: init task migrated from .gitpod.yml
        name: 'Task 0: init'